import Head from 'next/head'
import Header from '../components/Header'
import NavBar from '../components/NavBar'
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home({results}) {
  return (
    <div className=''>
      <Head>
        <title>IMDb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {/* Header */}
      <Header />
    {/* NavBar */}
      <NavBar />
    {/* Results */}
      <Results results={results} />
    </div>
  )
}

export async function getServerSideProps(context){
  const genre = context.query.genre || 'fetchTrending'

  const request = await fetch(`
  https://api.themoviedb.org/3${requests[genre].url}
  `).then(response => response.json())

  return{
    props:{
      results: request.results,
    }
  }
}